import Head from 'next/head'
import NextLink from 'next/link'
import { useRouter } from 'next/router'
import { Flex, Stack, Box, Container, Text, Link } from '@chakra-ui/react'

import { useUser } from '../contexts/UserContext'
import { supabase } from '../../lib/supabase'

const Layout = ({ children }) => {
  const router = useRouter()
  const { session } = useUser()

  console.log('layout session: ', session)

  const handleSignOut = async (e) => {
    e.preventDefault()
    const { error } = await supabase.auth.signOut()
    console.log('log out error', error)

    router.push('/')
  }

  return (
    <>
      <Head>
        <title>Profiles App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container maxW={'3xl'}>
        <Flex
          as="nav"
          w="100%"
          justify="space-between"
          alignItems="center"
          mb={8}
          py={4}
        >
          <Box>
            <Text fontSize="lg" fontWeight="bold">
              Profiles App
            </Text>
          </Box>

          <Stack spacing={4} align="center" direction="row">
            <Box>
              <NextLink href="/" passHref>
                <Link>Home</Link>
              </NextLink>
            </Box>

            <Box>
              <NextLink href="/rq" passHref>
                <Link>Home (react-query)</Link>
              </NextLink>
            </Box>

            {!session ? (
              <>
                <Box>
                  <NextLink href="/login" passHref>
                    <Link>Login</Link>
                  </NextLink>
                </Box>

                <Box>
                  <NextLink href="/signup" passHref>
                    <Link>Sign Up</Link>
                  </NextLink>
                </Box>
              </>
            ) : (
              <>
                <Box>
                  <NextLink href="/profile" passHref>
                    <Link>Profile</Link>
                  </NextLink>
                </Box>

                <Box>
                  <NextLink href="/settings" passHref>
                    <Link>Settings</Link>
                  </NextLink>
                </Box>

                <Box>
                  <Text onClick={handleSignOut}>Sign Out</Text>
                </Box>
              </>
            )}
          </Stack>
        </Flex>

        <Box>{children}</Box>
      </Container>
    </>
  )
}

export default Layout
