import Head from 'next/head'
import NextLink from 'next/link'
import { useRouter } from 'next/router'
import {
  Stack,
  Box,
  Center,
  Container,
  Button,
  Flex,
  Heading,
  Text,
  Link,
} from '@chakra-ui/react'

import { useUser } from '../lib/UserContext'
import { supabase } from '../util/supabase'

const Layout = ({ children }) => {
  const router = useRouter()
  const { session } = useUser()

  console.log('layout session: ', session)

  const handleSignOut = async (e) => {
    e.preventDefault()
    const { error } = await supabase.auth.signOut()
    console.log('log out error', error)

    router.push('/')
  }

  return (
    <>
      <Head>
        <title>Profiles App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container maxW={'3xl'}>
        <Stack as={Box} textAlign="center" py={{ base: 12 }}>
          <Heading
            fontWeight={600}
            fontSize={{ base: '2xl', sm: '4xl', md: '6xl' }}
          >
            Profiles App
          </Heading>

          <Stack direction={'row'} spacing={2}>
            <Box>
              <NextLink href="/" passHref>
                <Link>Home</Link>
              </NextLink>
            </Box>

            {!session ? (
              <>
                <Box>
                  <NextLink href="/login" passHref>
                    <Link>Login</Link>
                  </NextLink>
                </Box>

                <Box>
                  <NextLink href="/signup" passHref>
                    <Link>Sign Up</Link>
                  </NextLink>
                </Box>
              </>
            ) : (
              <>
                <Box>
                  <NextLink href="/profile" passHref>
                    <Link>Profile</Link>
                  </NextLink>
                </Box>

                <Box>
                  <Text onClick={handleSignOut}>Sign Out</Text>
                </Box>
              </>
            )}
          </Stack>
        </Stack>

        <Box>{children}</Box>
      </Container>
    </>
  )
}

export default Layout
