import { useState, useEffect } from 'react'
import Head from 'next/head'
import { supabase } from '../lib/supabase'
import Auth from '../components/Auth'
import Profile from '../components/Profile'

export default function Home() {
  const [session, setSession] = useState()

  useEffect(() => {
    setSession(supabase.auth.session())

    supabase.auth.onAuthStateChange((_event, session) => {
      setSession(session)
    })
  }, [])

  console.log('session', session)

  return (
    <div>
      <Head>
        <title>Profiles App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Welcome to the Profiles app</h1>

        <div>{session ? <Profile session={session} /> : <Auth />}</div>
      </main>
    </div>
  )
}
